#!/bin/bash

echo "Trying to create the venv in the folder: .venv"

python3 -m venv ../.venv

echo "Activating virtual environment"

. ../.venv/bin/activate

echo "Installing the dependencies"

pip install flask
pip install flask-bootstrap
pip install pytest
pip install pylint
