pipeline {
    agent any

    environment {
        PYTHONPATH = "${WORKSPACE}/app"
    }

    stages {
        stage('Build') {
            steps {
                sh '''
                echo "Building..."
                cd app
                ./activeaza_venv_jenkins
                '''
            }
        }

        stage('pylint - calitate cod') {
            steps {
                sh '''
                cd app
                . ./activeaza_venv
                echo "\nVerificare lib cu pylint"
                pylint --exit-zero lib/*.py
                echo "\nVerificare tests cu pylint"
                pylint --exit-zero tests/*.py
                '''
            }
        }

        stage('Unit Testing cu pytest') {
            steps {
                sh '''
                cd app
                . ./activeaza_venv
                export PYTHONPATH=$(pwd)
                python3 -m pytest -v tests/
                '''
            }
        }

        stage('Deploy') {
            steps {
                echo "Deploy stage (placeholder)..."
            }
        }
    }
}
